### ISSUE TITLE
OpenSSL 1.1.0 support

### ISSUE THREAD

**Issue by AlexanderPavlenko** [oleganza/btcruby#29]
```
/usr/local/bundle/gems/ffi-1.9.21/lib/ffi/library.rb:275:in `attach_function':
Function 'SSL_library_init' not found in [libssl.so] (FFI::NotFoundError)
  from /usr/local/bundle/gems/btcruby-1.7/lib/btcruby/openssl.rb:21:in `<module:OpenSSL>'

> openssl version
OpenSSL 1.1.0f  25 May 2017
```
Reproducible via `ruby:2.5.0` Docker image.
Related: https://github.com/lian/bitcoin-ruby/issues/205

**Comment by xaviablaza** [comment]
For Arch:
`sudo ln -nfs /usr/lib/libssl.so.1.0.0 /usr/lib/libssl.so`

**Comment by mtomov** [comment]
Thanks @AlexanderPavlenko  - really saved the day for CircleCi! Thanks!

**Comment by phuongnd08** [comment]
Wonder why libssl.so is suffixed with 1.0.2 while openssl version is 1.1.0?

**Comment by phuongnd08** [comment]
I see so openssl 1.1.0 come with both 1.1 and 1.0.2 shared object and btcruby only work with 1.0.2

**Comment by EugZol** [comment]
https://github.com/EugZol/btcruby/commit/9e3378a22dde83629cf672727dce964654bb8ba6  – try this one

Test suite is passing, but I've done no thorough testing beside that.
